#!/bin/sh -e
#
# pjs unit tests.

pjs () {
    ../bin/pjs "$@"
}

equals () {
    tmp="/tmp/test-pjs"
    echo -n "$1" | tail -n +2 > "$tmp"
    diff - "$tmp"
    rm "$tmp"
}

cd `dirname $(realpath "$0")`
set -v

seq 1 10 | pjs '_ > 5' | equals '
6
7
8
9
10
'

seq 1 10 | pjs '_ % 2 == 0' | equals '
2
4
6
8
10
'

cat data/lorem.txt | pjs '_.toUpperCase()' | equals '
LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. QUISQUE PULVINAR, ODIO
A ULTRICES FACILISIS, NISI LOREM TEMPUS LECTUS, VEL RUTRUM DOLOR ODIO A VELIT.
ALIQUAM PHARETRA MAXIMUS JUSTO, AC VESTIBULUM MASSA MOLESTIE NON. FUSCE EGET
QUAM ALIQUAM, VIVERRA QUAM QUIS, MAXIMUS NULLA. MAURIS TINCIDUNT UT TELLUS AT
TINCIDUNT. PROIN NEC EST MI. FUSCE SOLLICITUDIN ELIT ET CONSEQUAT VOLUTPAT. IN
AC VEHICULA ENIM.
'

cat data/lorem.txt | pjs --after 'LINES.slice(-3).join("\n")' | equals '
quam aliquam, viverra quam quis, maximus nulla. Mauris tincidunt ut tellus at
tincidunt. Proin nec est mi. Fusce sollicitudin elit et consequat volutpat. In
ac vehicula enim.
'

cat data/lorem.txt | pjs 'if (_.length > m) { m = _.length; longest = _ }' \
    --after 'longest' | equals '
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar, odio
'

cat data/lorem.txt | pjs 'count++ ;;' --after 'count' | equals '
6
'

cat data/lorem.txt | pjs --after 'COUNT' | equals '
6
'

# Not technically correct because empty lines are counted as words
cat data/lorem.txt | pjs 'words += $.length ;;' --after 'words' | equals '
62
'

# Not technically correct because words include punctuation
cat data/lorem.txt | pjs --before 'let words = new Set()' \
    'for (let word of $) words.add(word)' --after 'words.size' | equals '
55
'

cat data/whitespace.txt | pjs '_.replace(/\s*$/, "")' | equals '
This
  file has
    trailing
WHITESPACE !
'

cat data/passwd.txt | pjs -d : '$5' | equals '
/root
/usr/sbin
/bin
/dev
'

cat data/passwd.txt | pjs -d : '$.slice(0, 2)' | equals '
["root","x"]
["daemon","x"]
["bin","x"]
["sys","x"]
'

cat data/filenames.txt | pjs 'fs.existsSync(_)' | equals '
run
data/grades.csv
data/users.json
'

cat data/filenames.txt | pjs 'fs.existsSync(_) && fs.statSync(_).size > 200' | equals '
run
data/users.json
'

cat data/filenames.txt | pjs --before 'let s = new Set()' 's.add(_) ;;' \
    --after 's.size' | equals '
4
'

cat data/website.html | pjs --html 'title' '_.text.trim()' | equals '
Bob'\''s Homepage
'

cat data/website.html | pjs --html '#counter' '_.text' | equals '
1234
'

cat data/website.html | pjs --html 'img[src]' '_.attr.src' | equals '
construction.gif
dancing-baby.gif
'

cat data/simple.xml | pjs --xml 'item[kind=foo]' --after COUNT | equals '
2
'

cat data/simple.xml | pjs --xml 'ITEM' --after COUNT | equals '
1
'

cat data/aduros-website.html | pjs --html 'h1,h2' '_.text' | equals '
aduros.com
Hacking i3: Automatic Layout
Introducing pjs
Ramblings From a Dirty Apartment
Returning to Text
Hacking i3: Window Promoting
A Blog Half Full
Simple Clipboard Management
Firefox Minimalism
Media Companies are Complicit
Access Recent Files From the Command Line
'

cat data/aduros-website.html | pjs --html 'img' '_.attr.src' | equals '
/profile.jpg
'

cat data/aduros-website.html | pjs --html 'ul.c-links a[target=_blank]' '_.attr.href' | equals '
https://aduros.com/index.xml
https://twitter.com/b_garcia
https://github.com/aduros
https://linkedin.com/in/bruno-garcia-38223415
'

cat data/aduros-website.html | pjs --html 'h2 a' \
    '_.attr.href.includes("blog") ? _.attr.href : null' | equals '
https://aduros.com/blog/hacking-i3-automatic-layout/
https://aduros.com/blog/introducing-pjs/
https://aduros.com/blog/ramblings-from-a-dirty-apartment/
https://aduros.com/blog/returning-to-text/
https://aduros.com/blog/hacking-i3-window-promoting/
https://aduros.com/blog/a-blog-half-full/
https://aduros.com/blog/simple-clipboard-management/
https://aduros.com/blog/firefox-minimalism/
https://aduros.com/blog/media-companies-are-complicit/
https://aduros.com/blog/access-recent-files-from-the-command-line/
'

set +v
echo "All tests passed."
